# Generated by Django 5.0.1 on 2024-02-15 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sports',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'sports',
            },
        ),
        migrations.CreateModel(
            name='timezones',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('label_text', models.CharField(max_length=50)),
                ('offset_in_seconds', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'timezones',
            },
        ),
        migrations.CreateModel(
            name='sport_format',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('can_play_doubles', models.BooleanField(null=True)),
                ('can_play_singles', models.BooleanField(null=True)),
                ('default_set_count', models.BigIntegerField(default=1)),
                ('default_game_count', models.BigIntegerField(default=3)),
                ('default_set_score', models.BigIntegerField(default=0)),
                ('default_set_duration_in_mins', models.BigIntegerField()),
                ('is_from_tennis_family', models.BooleanField()),
                ('sport_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='racquet_heros_database.sports')),
            ],
            options={
                'verbose_name_plural': 'sport_format',
            },
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('flag', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('default_timezone_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='racquet_heros_database.timezones')),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='racquet_heros_database.countries')),
                ('timezone_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='racquet_heros_database.timezones')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
