# Generated by Django 5.0.1 on 2024-02-14 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timezones',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('label_text', models.CharField(max_length=50)),
                ('offset_in_seconds', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'timezones',
            },
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('flag', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('default_timezone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racquet_heros_database.timezones')),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racquet_heros_database.countries')),
                ('timezone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racquet_heros_database.timezones')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
